[theme]
primaryColor = "#FFB000"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFB000"
font = "monospace"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
