[theme]
primaryColor = "#FF4400"
backgroundColor = "#101010"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#E0E0E0"
font = "monospace"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
